// Interface automatically generated by schemas-to-ts

export interface Speech {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    speech1?: string;
    speech2?: string;
    speech3?: string;
  };
}
export interface Speech_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  speech1?: string;
  speech2?: string;
  speech3?: string;
}

export interface Speech_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  speech1?: string;
  speech2?: string;
  speech3?: string;
}

export interface Speech_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  speech1?: string;
  speech2?: string;
  speech3?: string;
}
