// Interface automatically generated by schemas-to-ts

export interface Pages {
  name: string;
  url: string;
}
export interface Pages_Plain {
  name: string;
  url: string;
}

export interface Pages_NoRelations {
  name: string;
  url: string;
}

