// Interface automatically generated by schemas-to-ts

import { AdminPanelRelationPropertyModification } from "./AdminPanelRelationPropertyModification";
import { Media, Media_Plain } from "./Media";

export interface HomePage {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    hero_img?: { data: Media };
    hero_text?: string;
  };
}
export interface HomePage_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  hero_img?: Media_Plain;
  hero_text?: string;
}

export interface HomePage_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  hero_img?: number;
  hero_text?: string;
}

export interface HomePage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  hero_img?: AdminPanelRelationPropertyModification<Media_Plain>;
  hero_text?: string;
}
