// Interface automatically generated by schemas-to-ts

import { Media } from "./Media";
import { Socials } from "./Socials";
import { Pages } from "./Pages";
import { Media_Plain } from "./Media";
import { Socials_Plain } from "./Socials";
import { Pages_Plain } from "./Pages";
import { Socials_NoRelations } from "./Socials";
import { Pages_NoRelations } from "./Pages";
import { AdminPanelRelationPropertyModification } from "./AdminPanelRelationPropertyModification";

export interface Layout {
  id: number;
  attributes: {
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    logo_img?: { data: Media };
    social: Socials[];
    pages: Pages[];
    site_title?: string;
    site_description?: string;
  };
}
export interface Layout_Plain {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  logo_img?: Media_Plain;
  social: Socials_Plain[];
  pages: Pages_Plain[];
}

export interface Layout_NoRelations {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  logo_img?: number;
  social: Socials_NoRelations[];
  pages: Pages_NoRelations[];
}

export interface Layout_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;
  updatedAt: Date;
  publishedAt?: Date;
  logo_img?: AdminPanelRelationPropertyModification<Media_Plain>;
  social: Socials_Plain[];
  pages: Pages_Plain[];
}
