// Interface automatically generated by schemas-to-ts

import { Media, Media_Plain } from "./Media";

export interface Socials {
  social_url?: string;
  social_img?: { data: Media };
  hidden?: boolean;
  name: string;
}
export interface Socials_Plain {
  social_url?: string;
  social_img?: Media_Plain;
  hidden?: boolean;
}

export interface Socials_NoRelations {
  social_url?: string;
  social_img?: number;
  hidden?: boolean;
}
