// Interface automatically generated by schemas-to-ts

export interface SpeechComponent {
  speech?: string;
}
export interface SpeechComponent_Plain {
  speech?: string;
}

export interface SpeechComponent_NoRelations {
  speech?: string;
}

