// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Socials } from '../../../../components/socials/interfaces/Socials';
import { Pages } from '../../../../components/pages/interfaces/Pages';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Socials_Plain } from '../../../../components/socials/interfaces/Socials';
import { Pages_Plain } from '../../../../components/pages/interfaces/Pages';
import { Socials_NoRelations } from '../../../../components/socials/interfaces/Socials';
import { Pages_NoRelations } from '../../../../components/pages/interfaces/Pages';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Layout {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    logo_img?: { data: Media };
    social: Socials[];
    pages: Pages[];
    site_description?: string;
    site_title?: string;
  };
}
export interface Layout_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo_img?: Media_Plain;
  social: Socials_Plain[];
  pages: Pages_Plain[];
  site_description?: string;
  site_title?: string;
}

export interface Layout_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo_img?: number;
  social: Socials_NoRelations[];
  pages: Pages_NoRelations[];
  site_description?: string;
  site_title?: string;
}

export interface Layout_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo_img?: AdminPanelRelationPropertyModification<Media_Plain>;
  social: Socials_Plain[];
  pages: Pages_Plain[];
  site_description?: string;
  site_title?: string;
}
